pipeline {
    agent any

    stages {

        stage('Clonage') {
            steps {
                git 'https://github.com/Nchris1/monnom-flask-app.git'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t christelle-flask-app .'
            }
        }

        stage('Push DockerHub') {
            steps {
                sh 'docker tag christelle-flask-app chrisnto/christelle-flask-app'
                sh 'docker push chrisnto/christelle-flask-app'
            }
        }
    }
}
