pipeline {
    agent any

    stages {

        stage('Clonage') {
            steps {
                git branch: 'main', url: 'https://github.com/Nchris1/monnom-flask-app.git'
            }
        }

        stage('Build Image') {
            steps {
                sh 'docker build -t christelle-flask-app .'
            }
        }

        stage('Publication') {
            steps {
                sh 'docker tag christelle-flask-app Nchris1/christelle-flask-app'
                sh 'docker push Nchris1/christelle-flask-app'
            }
        }
    }
}
